name: archive
version: 3.4.10
description: >-
  Provides encoders and decoders for various archive and compression formats
  such as zip, tar, bzip2, gzip, and zlib.
repository: https://github.com/brendan-duncan/archive
environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  path: ^1.8.0
  pointycastle: ^3.7.3

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.1
  test: ^1.24.6
