name: archive
version: 4.0.7
description: >-
  Provides encoders and decoders for various archive and compression formats
  such as zip, tar, bzip2, gzip, and zlib.
repository: https://github.com/brendan-duncan/archive
topics:
  - archive
  - zip
  - tar
  - gzip
  - xz
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  path: ^1.8.0
  posix: ^6.0.2

dev_dependencies:
  build_runner: ^2.4.14
  build_web_compilers: ^4.1.0
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.6
  web: ^1.1.0
